export const aboutPageSeed = {
  title: 'About Amazing Hauling',
  slug: 'about',
  layout: [
    {
      blockType: 'hero',
      badge: 'About Us',
      headingLine1: 'Built on Hard Work,',
      headingLine2: 'Reliability,',
      headingLine3: 'and Trust',
      description: 'Amazing Hauling of North Florida is a family-owned hauling company based in Jacksonville, Florida, operated under the parent company Amazing Investments LLC.',
      primaryCta: 'Request a Quote',
      primaryCtaLink: '/contact',
      short: true,
    },
    {
      blockType: 'contentSplit',
      badge: 'Our Story',
      heading: 'From One Truck to a Growing Fleet',
      body: 'Founded by Antoine Pearson, Amazing Hauling began with a single truck and a commitment to doing quality work for every customer. Through dedication, reliability, and strong relationships with contractors, the company has grown into a trusted hauling partner supporting construction and development projects across Northeast Florida. Today, Amazing Hauling continues to expand while maintaining the same values that started the business: dependability, integrity, and service. Before starting the company, Antoine worked in the trucking and construction support field, learning how hauling operations support road construction and development projects throughout the region. With that experience, he launched Amazing Hauling with a vision of building a company known for reliable service and strong work ethic. What started as one truck has grown into a fleet supporting contractors across Jacksonville and the surrounding counties. The company continues to grow through hard work, word-of-mouth referrals, and a commitment to doing every job right.',
      ctaLabel: 'View Our Work',
      ctaLink: '/projects',
      reverse: false,
      overlap: true,
      background: 'white',
    },
    {
      blockType: 'contentSplit',
      badge: 'Family Owned',
      heading: 'A Family-Owned Company',
      body: 'Amazing Hauling is more than just a hauling company — it is a family business built on shared values and long-term vision. Antoine and Nikki Pearson work together to operate and grow the company while building a legacy for their family. Their goal is to create a company that represents professionalism, reliability, and strong relationships with clients throughout Northeast Florida. Being family-owned means every project matters, and every client relationship is valued.',
      reverse: true,
      overlap: true,
      background: 'cream',
    },
    {
      blockType: 'textBlock',
      badge: 'Our Mission',
      heading: 'Our Mission',
      body: 'To provide dependable hauling services that contractors and construction professionals can rely on to keep their projects moving safely and efficiently.',
      centered: true,
      background: 'black',
    },
    {
      blockType: 'textBlock',
      badge: 'Our Vision',
      heading: 'Our Vision',
      body: 'To become one of the most trusted hauling companies in Northeast Florida by delivering consistent service, maintaining strong partnerships, and continuing to grow our fleet and capabilities.',
      centered: true,
      background: 'cream',
    },
    {
      blockType: 'valuesGrid',
      heading: 'Our Core Values',
      columns: '2',
      background: 'white',
      items: [
        { icon: 'Shield', title: 'Dependability', description: 'When contractors schedule hauling, they need confidence that the trucks will arrive on time and ready to work. Dependability is the foundation of our business.' },
        { icon: 'Award', title: 'Integrity', description: 'We operate with honesty, professionalism, and respect for every client and job site we serve.' },
        { icon: 'MessageSquare', title: 'Communication', description: 'Clear communication helps projects run smoothly. We make sure contractors always know the status of their hauling operations.' },
        { icon: 'HardHat', title: 'Safety', description: 'Safety is a top priority in everything we do. Our drivers operate with professionalism and awareness to protect job sites, workers, and communities.' },
      ],
    },
    {
      blockType: 'contentSplit',
      badge: 'Regional Growth',
      heading: 'Growing With Northeast Florida',
      body: 'Jacksonville and the surrounding region continue to grow through new infrastructure, road construction, and development projects. Amazing Hauling is proud to play a role in supporting that growth by providing reliable hauling services that keep construction projects moving forward. As the company continues to expand, our focus remains the same: Deliver dependable service, build strong relationships, and earn the trust of every contractor we work with.',
      reverse: false,
      overlap: true,
      background: 'white',
    },
    {
      blockType: 'fleet',
      heading: 'Our Fleet',
      body: 'Amazing Hauling currently operates three dump trucks and continues to invest in additional equipment as the business grows. Our goal is to expand our fleet while maintaining the same high standards of reliability and professionalism that our clients expect.',
      metrics: [
        { icon: 'Truck', value: '3', label: 'Trucks in Operation' },
        { icon: 'TrendingUp', value: '4+', label: 'Planned Expansion' },
        { icon: 'MapPin', value: 'NE FL', label: 'Service Region' },
        { icon: 'Users', value: '100%', label: 'Family-Owned' },
      ],
    },
    {
      blockType: 'ctaBanner',
      heading: 'Work With a Company That Shows Up',
      description: 'Contractors need hauling partners they can depend on. Amazing Hauling is committed to delivering reliable service, clear communication, and professional support for every project. If your project needs dependable hauling, we\'re ready to help.',
      primaryCta: 'Request a Quote',
      primaryCtaLink: '/contact',
      secondaryCta: 'Call Now',
      secondaryCtaLink: 'tel:',
    },
  ],
  meta: {
    title: 'About Amazing Hauling',
    description: 'Learn about Amazing Hauling of North Florida. A family-owned hauling company based in Jacksonville, founded by Antoine Pearson, committed to dependability, integrity, and service.',
  },
}
