function createSeoPage(slug: string, city: string, county: string, heading: string, description: string, servicesIntro: string, servicesItems: string[], supportContent: string) {
  return {
    title: heading,
    slug: `areas/${slug}`,
    layout: [
      {
        blockType: 'hero',
        imageKey: slug === 'jacksonville' ? 'convoy' : slug === 'fernandina-beach' ? 'dirtHaul' : slug === 'orange-park' ? 'replacementTruck' : slug === 'st-augustine' ? 'materialsHauling' : 'convoyAlt',
        badge: 'Service Area',
        headingLine1: heading,
        description,
        primaryCta: 'Request a Quote',
        primaryCtaLink: '/contact',
        secondaryCta: 'Call Now',
        secondaryCtaLink: 'tel:',
        short: true,
      },
      {
        blockType: 'textBlock',
        heading: description,
        body: `${city} and ${county} continue to experience strong growth, creating demand for reliable hauling services. Amazing Hauling provides dependable hauling services for contractors and development projects throughout ${city} and surrounding areas. Our fleet helps contractors move materials efficiently so projects can stay on schedule.`,
        centered: true,
        background: 'white',
      },
      {
        blockType: 'serviceCards',
        heading: `Hauling Services in ${city}`,
        description: servicesIntro,
        items: servicesItems.map((item) => ({
          title: item,
          description: `Reliable ${item.toLowerCase()} services for contractors in ${city}.`,
          icon: 'Truck',
        })),
      },
      {
        blockType: 'textBlock',
        heading: supportContent.split('.')[0],
        body: supportContent,
        centered: true,
        background: 'cream',
      },
      {
        blockType: 'ctaBanner',
        heading: `Request Hauling Services in ${city}`,
        description: `If your project needs dependable dump truck hauling in ${city}, Amazing Hauling is ready to help. Call today or request a quote to schedule hauling services for your job site.`,
        primaryCta: 'Request a Quote',
        primaryCtaLink: '/contact',
        secondaryCta: 'Call Now',
        secondaryCtaLink: 'tel:',
      },
    ],
    meta: {
      title: `${heading} | Amazing Hauling of North Florida`,
      description,
      imageKey: slug === 'jacksonville' ? 'convoy' : slug === 'fernandina-beach' ? 'dirtHaul' : slug === 'orange-park' ? 'replacementTruck' : slug === 'st-augustine' ? 'materialsHauling' : 'convoyAlt',
    },
  }
}

export const seoPageSeeds = [
  createSeoPage(
    'jacksonville',
    'Jacksonville',
    'Duval County',
    'Jacksonville Dump Truck Hauling',
    'Reliable Dump Truck Hauling in Jacksonville, Florida',
    'Amazing Hauling supports contractors throughout Jacksonville with a wide range of hauling services.',
    ['Dirt hauling and fill material transport', 'Asphalt hauling for paving projects', 'Rock and aggregate delivery', 'Milling debris hauling', 'Construction site material transport', 'Jobsite debris removal'],
    'Jacksonville continues to experience strong growth with new infrastructure projects, residential developments, and commercial construction across the city. Amazing Hauling works alongside contractors to help move the materials that support this growth. Our drivers understand the demands of active job sites and work carefully to ensure materials are transported safely and on time.',
  ),
  createSeoPage(
    'fernandina-beach',
    'Fernandina Beach',
    'Nassau County',
    'Dirt Hauling in Fernandina Beach',
    'Dirt Hauling Services in Fernandina Beach, Florida',
    'Amazing Hauling provides dependable dirt hauling services for contractors and development projects throughout Fernandina Beach.',
    ['Excavated dirt removal', 'Fill dirt transport', 'Construction site dirt hauling', 'Development site preparation', 'Land clearing projects'],
    'Amazing Hauling is proud to support construction crews and developers working throughout Nassau County. Our hauling services help contractors complete projects faster by providing dependable trucking support when materials need to be moved quickly.',
  ),
  createSeoPage(
    'orange-park',
    'Orange Park',
    'Clay County',
    'Dump Truck Services in Orange Park',
    'Dump Truck Hauling in Orange Park, Florida',
    'Amazing Hauling provides hauling services for a variety of construction materials in Orange Park.',
    ['Dirt and fill material', 'Rock and aggregates', 'Asphalt materials', 'Construction debris', 'Milling debris'],
    'Clay County contractors rely on dependable hauling partners to move materials safely and efficiently between job sites. Amazing Hauling works alongside construction teams to ensure materials arrive when they are needed.',
  ),
  createSeoPage(
    'st-augustine',
    'St. Augustine',
    'St. Johns County',
    'Aggregate Hauling in St. Augustine',
    'Aggregate Delivery & Hauling in St. Augustine, Florida',
    'Amazing Hauling regularly transports construction aggregates for contractors in St. Augustine.',
    ['Granite stone', 'Gravel', 'Crushed rock', 'Base materials', 'Construction aggregates'],
    'Our team works closely with contractors to provide dependable hauling services that support development projects across St. Johns County. We focus on providing professional service that contractors can trust.',
  ),
  createSeoPage(
    'yulee',
    'Yulee',
    'Nassau County',
    'Dump Truck Hauling in Yulee',
    'Dump Truck Services in Yulee, Florida',
    'Our hauling services support contractors with transporting materials needed for development and construction projects in Yulee.',
    ['Dirt hauling', 'Aggregate delivery', 'Asphalt hauling', 'Construction debris removal', 'Jobsite materials transport'],
    'Amazing Hauling works alongside contractors throughout Nassau County to ensure construction projects have dependable hauling support. Our drivers understand the importance of reliable service and professional jobsite conduct.',
  ),
]
