export const servicesPageSeed = {
  title: 'Services',
  slug: 'services',
  layout: [
    {
      blockType: 'hero',
      imageKey: 'asphaltAction',
      badge: 'Our Services',
      headingLine1: 'Reliable Materials',
      headingLine2: 'Hauling Services',
      description: 'Amazing Hauling of North Florida provides dependable dump truck hauling services for contractors, construction crews, and development teams throughout Jacksonville and Northeast Florida.',
      primaryCta: 'Request a Quote',
      primaryCtaLink: '/contact',
      short: true,
    },
    {
      blockType: 'textBlock',
      heading: 'Reliable Materials Hauling Services',
      body: 'We understand that hauling is a critical part of keeping projects moving forward. Our team focuses on safe operations, predictable scheduling, and clear communication, ensuring every job runs smoothly from start to finish. Whether you need dirt transported, asphalt delivered, or aggregates hauled to a job site, Amazing Hauling is ready to support your project.',
      centered: true,
      background: 'white',
    },
    {
      blockType: 'serviceCards',
      heading: 'Our Hauling Services',
      items: [
        { icon: 'Mountain', title: 'Dirt & Fill Hauling', description: 'Site preparation and development projects often require moving large amounts of dirt and fill material.', bulletPoints: [{ item: 'Excavated dirt removal' }, { item: 'Fill dirt transport' }, { item: 'Construction site dirt hauling' }, { item: 'Land development site support' }, { item: 'Dirt relocation between job sites' }] },
        { icon: 'Route', title: 'Asphalt Hauling', description: 'Road construction and paving operations rely on dependable hauling partners to move asphalt efficiently.', bulletPoints: [{ item: 'Hot asphalt transport from plants to job sites' }, { item: 'Asphalt debris hauling' }, { item: 'Road resurfacing support' }, { item: 'Asphalt paving project logistics' }] },
        { icon: 'Gem', title: 'Aggregates & Rock Delivery', description: 'Construction projects require a steady supply of aggregate materials.', bulletPoints: [{ item: 'Granite stone' }, { item: 'Gravel' }, { item: 'Crushed rock' }, { item: 'Base materials' }, { item: 'Construction aggregates' }] },
        { icon: 'Trash2', title: 'Milling & Road Debris Hauling', description: 'Road resurfacing and asphalt milling operations produce large volumes of debris that must be removed quickly.', bulletPoints: [{ item: 'Asphalt milling debris transport' }, { item: 'Road resurfacing support' }, { item: 'Roadway cleanup hauling' }, { item: 'Material relocation from milling operations' }] },
        { icon: 'Building2', title: 'Construction Site Materials Transport', description: 'Many projects require ongoing hauling of materials between sites, suppliers, and staging areas.', bulletPoints: [{ item: 'Jobsite material delivery' }, { item: 'Debris hauling' }, { item: 'Construction waste removal' }, { item: 'Site logistics support' }] },
        { icon: 'Handshake', title: 'Subcontract Hauling Services', description: 'Large projects often require additional hauling capacity. Amazing Hauling works as a subcontractor for larger contractors.', bulletPoints: [{ item: 'Additional hauling trucks when needed' }, { item: 'Reliable scheduling support' }, { item: 'Professional drivers and equipment' }, { item: 'Consistent communication throughout the project' }] },
      ],
    },
    {
      blockType: 'contentSplit',
      imageKey: 'worksite',
      badge: 'Industries We Support',
      heading: 'Working Across Multiple Industries',
      body: 'Amazing Hauling regularly works with professionals across multiple industries including road construction contractors, asphalt paving companies, site development companies, residential developers, commercial construction teams, and municipal infrastructure projects. Our experience working with these industries allows us to understand jobsite expectations and deliver dependable service.',
      reverse: true,
      overlap: true,
      background: 'cream',
    },
    {
      blockType: 'contentSplit',
      imageKey: 'fleetAlt',
      badge: 'Safety First',
      heading: 'Safety & Professional Standards',
      body: 'Safety is a core part of how Amazing Hauling operates. Our drivers follow strict safety practices while operating on job sites, roadways, and construction environments. We are committed to professional jobsite conduct, safe equipment operation, compliance with industry standards, and protecting crews and communities. Contractors can trust that Amazing Hauling operates with professionalism and responsibility on every project.',
      ctaLabel: 'Learn About Our Team',
      ctaLink: '/about',
      reverse: false,
      overlap: true,
      background: 'white',
    },
    {
      blockType: 'ctaBanner',
      imageKey: 'asphaltAction',
      heading: 'Need Hauling for Your Project?',
      description: 'Amazing Hauling is ready to support your next project with dependable dump truck services. Request a quote today to schedule hauling services for your job site.',
      primaryCta: 'Request a Quote',
      primaryCtaLink: '/contact',
      secondaryCta: 'Call Now',
      secondaryCtaLink: 'tel:',
    },
  ],
  meta: {
    title: 'Hauling Services | Amazing Hauling of North Florida',
    description: 'Dependable dump truck hauling services for contractors in Jacksonville and Northeast Florida. Dirt, asphalt, aggregates, milling debris, and construction materials hauling.',
    imageKey: 'asphaltPaving',
  },
}
