export const subcontractorPageSeed = {
  title: 'Subcontractor Resources',
  slug: 'subcontractor-resources',
  layout: [
    {
      blockType: 'hero',
      imageKey: 'replacementTruckAlt',
      badge: 'Partner With Us',
      headingLine1: 'Subcontractor',
      headingLine2: 'Resources',
      description: 'Partner With Amazing Hauling',
      primaryCta: 'Contact Us',
      primaryCtaLink: '/contact',
      short: true,
    },
    {
      blockType: 'textBlock',
      heading: 'Partner With Amazing Hauling',
      body: 'Amazing Hauling of North Florida works with trusted trucking partners to support larger construction and infrastructure projects throughout the region. When projects require additional hauling capacity, we partner with reliable subcontractors to ensure contractors receive the dependable service they expect. If you are a dump truck owner or trucking company interested in working with Amazing Hauling, we welcome the opportunity to partner with you.',
      centered: true,
      background: 'white',
    },
    {
      blockType: 'valuesGrid',
      heading: 'Why Work With Amazing Hauling',
      columns: '2',
      background: 'cream',
      items: [
        { icon: 'Briefcase', title: 'Consistent Work Opportunities', description: 'Large projects often require additional trucks, and we regularly work with subcontract drivers to support project demand.' },
        { icon: 'MessageSquare', title: 'Clear Communication', description: 'We coordinate hauling operations carefully so subcontractors understand expectations, schedules, and project requirements.' },
        { icon: 'Award', title: 'Professional Jobsite Standards', description: 'We maintain a high level of professionalism on job sites and expect the same from our subcontract partners.' },
        { icon: 'Handshake', title: 'Long-Term Partnerships', description: 'Our goal is to build lasting relationships with dependable trucking professionals who can support projects as our company continues to grow.' },
      ],
    },
    {
      blockType: 'contentSplit',
      imageKey: 'fleetAlt',
      badge: 'Requirements',
      heading: 'Subcontractor Requirements',
      body: 'To ensure safe and reliable operations, subcontract drivers working with Amazing Hauling should meet standard industry requirements. Typical requirements include: Valid commercial driver\'s license (CDL) if required, properly insured trucks and equipment, compliance with safety regulations, professional jobsite conduct, and ability to communicate clearly with dispatch and project supervisors. Additional documentation may be required depending on project requirements.',
      reverse: false,
      overlap: true,
      background: 'white',
    },
    {
      blockType: 'contentSplit',
      imageKey: 'siteDetail',
      badge: 'Get Started',
      heading: 'Subcontractor Packet',
      body: 'If you are interested in working with Amazing Hauling, please download and complete our subcontractor packet. The packet includes forms and information necessary to begin working with our team. After completing the forms, please submit the packet to info@amazinghauling.com.',
      ctaLabel: 'Contact Our Team',
      ctaLink: '/contact',
      reverse: true,
      overlap: true,
      background: 'cream',
    },
    {
      blockType: 'textBlock',
      heading: 'Growing Together',
      body: 'Amazing Hauling is a growing company, and strong subcontract partnerships help us support larger projects across Northeast Florida. By working together, we can provide contractors with the dependable hauling capacity they need to complete their projects successfully. If you are a professional truck driver or trucking company looking for new opportunities, we look forward to working with you.',
      centered: true,
      background: 'white',
    },
    {
      blockType: 'ctaBanner',
      imageKey: 'replacementTruck',
      heading: 'Interested in Partnering With Us?',
      description: 'If you would like to work with Amazing Hauling on upcoming projects, download the subcontractor packet and submit your information today.',
      primaryCta: 'Contact Our Team',
      primaryCtaLink: '/contact',
    },
  ],
  meta: {
    title: 'Subcontractor Resources',
    description: 'Partner with Amazing Hauling. Download our subcontractor packet and learn about opportunities for dump truck owners and trucking companies in Northeast Florida.',
    imageKey: 'replacementTruckAlt',
  },
}
